### ISSUE TITLE
SQL Script

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#12]
1 - Missing ID number in the inserts. The ID starts with 1 and not 0.
2 - Call the ID key id_[table_name] (e.g id_user, id_role, etc.)
3 - The comments must be in english (e.g "Criptare md5 le password") as reported in the issue #5 
4 - The relationship between user and role must be 1-n side of user and 0-n side of role
5 - Add two usesr with role administrator and set real personal information: Daniele Tellina and Alexander Perucci
6- check and fix all inserts with correct values and no template value

**Comment by dantel19** [comment]
Closed with commit 97313f04bdf3824207ae73f797f7e9915a093eb9
