### ISSUE TITLE
Use space ony and no tabs

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#13]
Make attention when you use the Eclipse XML format. The license header of the pom file is unformatted, adjust it.

Don't use tabs to indent, use space only. You can set this in the Eclipse Preferences. Check all files,

![image](https://cloud.githubusercontent.com/assets/6408950/21853281/c562ace0-d816-11e6-84a9-f98671a08762.png)

![image](https://cloud.githubusercontent.com/assets/6408950/21853352/0c4d2914-d817-11e6-80dd-613e9100dc0d.png)

![image](https://cloud.githubusercontent.com/assets/6408950/21853392/361a48d0-d817-11e6-9f69-f570bddcc815.png)

**Comment by dantel19** [comment]
Closed with commit 18d7362667014402582465ac7564627354d0ab75
