### ISSUE TITLE
SQL Warning

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#14]
I have execute the SQL script and I have this warning:

11:32:04	SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO'	0 row(s) affected, 1 warning(s): 3090 Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.	0.000 sec

Please fix it.

**Comment by dantel19** [comment]
Closed with commit f73c6c7e635d9b69b334fe3add0dd1e931958f83
