### ISSUE TITLE
Missing license and author information

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#2]
Add in each file the license information and in each *.java file the author information

**Comment by alexander-perucci** [comment]
Change the license header in the file [build-tomcat](https://github.com/dantel19/profile-manager/blob/master/src/main/assembly/build-tomcat.xml)

**Comment by dantel19** [comment]
Closed with commit d33b1c2e05862dd004a5eda5fd1389735c73bd74
