### ISSUE TITLE
Question about InformationProfileId

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#27]
What is and what is for the class `InformationProfileId` ?

**Comment by dantel19** [comment]
The class ProfileInformationId (renamed ProfileInformtionPK for clarity) is required to map the composite primary key in profile_information database table generated by the association ManyToMany between "information" and "profile".

This solution is described in the official Oracle documentation.
ref link:
https://docs.oracle.com/cd/E16439_01/doc.1013/e13981/cmp30cfg001.htm
