### ISSUE TITLE
Remove Alexander Perucci Copyright

### ISSUE THREAD

**Issue by alexander-perucci** [dantel19/profile-manager#3]
In each license information:
remove this line: Profile Manager - Copyright (C) 2016  Alexander Perucci (http://www.alexanderperucci.com/).

and let only this: Profile Manager - Copyright (C) 2016  Daniele Tellina.

don't specify your website (i.e in the pom file, license header, etc.) if you don't have it.

**Comment by dantel19** [comment]
Closed with commit 8412184a0b8ee432630dee11593a70be25fbbda7
